//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofire.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofire.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Interval.
        /// </summary>
        public static string ActionInterval {
            get {
                return ResourceManager.GetString("ActionInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seconds.
        /// </summary>
        public static string ActionIntervalUnit {
            get {
                return ResourceManager.GetString("ActionIntervalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Function Key.
        /// </summary>
        public static string ActionKey {
            get {
                return ResourceManager.GetString("ActionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Skill Name.
        /// </summary>
        public static string ActionSkillName {
            get {
                return ResourceManager.GetString("ActionSkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create New Profile.
        /// </summary>
        public static string ConfigCreate {
            get {
                return ResourceManager.GetString("ConfigCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter a name to create new.
        /// </summary>
        public static string ConfigCreateTitle {
            get {
                return ResourceManager.GetString("ConfigCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Refresh Profile and List.
        /// </summary>
        public static string ConfigRefresh {
            get {
                return ResourceManager.GetString("ConfigRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove Profile.
        /// </summary>
        public static string ConfigRemove {
            get {
                return ResourceManager.GetString("ConfigRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want remove this profile?.
        /// </summary>
        public static string ConfigRemoveTitle {
            get {
                return ResourceManager.GetString("ConfigRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rename Profile.
        /// </summary>
        public static string ConfigRename {
            get {
                return ResourceManager.GetString("ConfigRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter a new name to rename.
        /// </summary>
        public static string ConfigRenameTitle {
            get {
                return ResourceManager.GetString("ConfigRenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Management.
        /// </summary>
        public static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you having fun with Autofire? Please, consider make a donation to support the creation of new features!.
        /// </summary>
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bring Target Window to Front.
        /// </summary>
        public static string GameIdentifyWindow {
            get {
                return ResourceManager.GetString("GameIdentifyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select Target Window.
        /// </summary>
        public static string GameSelectWindow {
            get {
                return ResourceManager.GetString("GameSelectWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Global Mode ON/OFF.
        /// </summary>
        public static string HotkeyGlobalMode {
            get {
                return ResourceManager.GetString("HotkeyGlobalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter a Hotkey to Activate Macro.
        /// </summary>
        public static string MacroHotkey {
            get {
                return ResourceManager.GetString("MacroHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter a Hotkey.
        /// </summary>
        public static string MacroModalTitle {
            get {
                return ResourceManager.GetString("MacroModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enable/Disable Macro .
        /// </summary>
        public static string MacroOnOff {
            get {
                return ResourceManager.GetString("MacroOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Repeat Macro ON/OFF.
        /// </summary>
        public static string MacroRepeatMode {
            get {
                return ResourceManager.GetString("MacroRepeatMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        public static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ctrl + 1.
        /// </summary>
        public static string ProfileMacroHotkey {
            get {
                return ResourceManager.GetString("ProfileMacroHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consumable.
        /// </summary>
        public static string ProfileMacroName1 {
            get {
                return ResourceManager.GetString("ProfileMacroName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Skills.
        /// </summary>
        public static string ProfileMacroName2 {
            get {
                return ResourceManager.GetString("ProfileMacroName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Specials.
        /// </summary>
        public static string ProfileMacroName3 {
            get {
                return ResourceManager.GetString("ProfileMacroName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profile Manager.
        /// </summary>
        public static string ProfileManager {
            get {
                return ResourceManager.GetString("ProfileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CharName.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Run!.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop!.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
    }
}
